// Interface automatically generated by schemas-to-ts

export interface Damaging {
  damageaamount?: number;
  ignorevulnerability?: boolean;
}
export interface Damaging_Plain {
  damageaamount?: number;
  ignorevulnerability?: boolean;
}

export interface Damaging_NoRelations {
  damageaamount?: number;
  ignorevulnerability?: boolean;
}

