// Interface automatically generated by schemas-to-ts

export interface Healing {
  healingamount?: number;
}
export interface Healing_Plain {
  healingamount?: number;
}

export interface Healing_NoRelations {
  healingamount?: number;
}

