// Interface automatically generated by schemas-to-ts

import { Mechanic } from '../../../../components/mechanic/interfaces/Mechanic';
import { Mechanic_Plain } from '../../../../components/mechanic/interfaces/Mechanic';
import { Mechanic_NoRelations } from '../../../../components/mechanic/interfaces/Mechanic';

export interface Skill {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    description?: string;
    imageurl?: string;
    cooldown?: number;
    manacost?: number;
    mechanic: Mechanic[];
    remainingCooldown?: number;
  };
}
export interface Skill_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  imageurl?: string;
  cooldown?: number;
  manacost?: number;
  mechanic: Mechanic_Plain[];
  remainingCooldown?: number;
}

export interface Skill_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  imageurl?: string;
  cooldown?: number;
  manacost?: number;
  mechanic: Mechanic_NoRelations[];
  remainingCooldown?: number;
}

export interface Skill_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  imageurl?: string;
  cooldown?: number;
  manacost?: number;
  mechanic: Mechanic_Plain[];
  remainingCooldown?: number;
}
